
com:
  fastdfs:
    demo:
      fileStoreDirectory: C:/dfsfiles/
# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    #- 5.180.76.114:22122
    - 172.16.124.165:22122
    - 172.16.124.164:22122
#webServerUrl: http://172.16.124.164/